### ISSUE TITLE
Blank line if indenter is elastic

### ISSUE THREAD

**Issue by vkeryvin** [lcharleux/argiope#1]
If the indenter is assumed elastic, there's a blank line created after *ELASTIC and the properties line that makes the calculation crash

**Comment by lcharleux** [comment]
Corrected by materials full rewrite this evening.

**Comment by vkeryvin** [comment]
After corrections, got this message for the example indentation_2D
model0 = hd.models.Indentation2D(label = label, 
                      meshes = meshes, 
                      steps = steps, 
                      materials = materials, 
                      solver = "abaqus", 
                      solver_path = local_settings.ABAQUS_PATH,
                      workdir = workdir,
                      verbose = True)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-9a506b87a9b8> in <module>()
     96                       solver_path = local_settings.ABAQUS_PATH,
     97                       workdir = workdir,
---> 98                       verbose = True)
     99 

TypeError: __init__() got an unexpected keyword argument 'meshes'
